#cloud-config
packages:
  - docker

write_files:
  - path: /root/.cloudflared/tun-credentials.json
    owner: root:root
    permissions: '0600'
    content: |
      {
        "AccountTag":"XXXX",
        "TunnelSecret":"XXXXX",
        "TunnelID":"${TUNNEL_ID}"
      }

  - path: /root/.cloudflared/config.yml
    owner: root:root
    permissions: '0600'
    content: |
      tunnel: ${TUNNEL_ID}
      credentials-file: /root/.cloudflared/tun-credentials.json

      ingress:
        - hostname: tun2.XXXXX.xyz
          service: http://localhost:3000
        - hostname: ssh.XXXX.xyz
          service: ssh://localhost:22
        - service: http_status:404

runcmd:
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker ec2-user

  # Add Cloudflare Tunnel
  - wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
  - sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
  - sudo chmod +x /usr/local/bin/cloudflared
  - sudo cloudflared service install
  - sudo systemctl start cloudflared
  - sudo systemctl enable cloudflared

  # Add swap space
  - sudo dd if=/dev/zero of=/mnt/ssd-swapfile bs=1M count=$((INSTANCE_SWAP_SIZE*1024))
  - sudo chmod 600 /mnt/ssd-swapfile
  - sudo mkswap /mnt/ssd-swapfile
  - sudo swapon /mnt/ssd-swapfile
  - echo '/mnt/ssd-swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  - echo "vm.swappiness=10" | sudo tee -a /etc/sysctl.conf
  - sudo sysctl -p
