name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.BACKEND_BUCKET_NAME }}"

      - name: Terraform Apply
        env:
          TF_VAR_portainer_password: ${{ secrets.PORTAINER_PASS }}
          TF_VAR_nginx_proxy_manager_email: ${{ secrets.NGINX_PM_USER }}
          TF_VAR_nginx_proxy_manager_password: ${{ secrets.NGINX_PM_PASS }}
        run: |
          terraform destroy -auto-approve